// <copyright file="PostExtendedPriceListItemUpdate.cs" company="">
// Copyright (c) 2017 All Rights Reserved
// </copyright>
// <author></author>
// <date>7/14/2017 12:36:41 PM</date>
// <summary>Implements the PostExtendedPriceListItemUpdate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.ExtendedPriceListItem;

    /// <summary>
    /// PostExtendedPriceListItemUpdate Plugin.
    /// Fires when the following attributes are updated:
    /// All Attributes
    /// </summary>    
    public class PostExtendedPriceListItemUpdate: Plugin
    {
        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes before the core platform operation executes.
        /// The image contains the following attributes:
        /// No Attributes
        /// </summary>
        private readonly string preImageAlias = "preImage";

        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes after the core platform operation executes.
        /// The image contains the following attributes:
        /// No Attributes
        /// 
        /// Note: Only synchronous post-event and asynchronous registered plug-ins 
        /// have PostEntityImages populated.
        /// </summary>
        private readonly string postImageAlias = "postImage";

        /// <summary>
        /// Initializes a new instance of the <see cref="PostExtendedPriceListItemUpdate"/> class.
        /// </summary>
        public PostExtendedPriceListItemUpdate()
            : base(typeof(PostExtendedPriceListItemUpdate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Update", "gsc_cmn_extendedpricelistitem", new Action<LocalPluginContext>(ExecutePostExtendedPriceListItemUpdate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostExtendedPriceListItemUpdate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;

            Entity preImageEntity = (context.PreEntityImages != null && context.PreEntityImages.Contains(this.preImageAlias)) ? context.PreEntityImages[this.preImageAlias] : null;
            Entity postImageEntity = (context.PostEntityImages != null && context.PostEntityImages.Contains(this.postImageAlias)) ? context.PostEntityImages[this.postImageAlias] : null;

           IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;
            Entity extendedEntity = (Entity)context.InputParameters["Target"];

            if (!(context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity)) { return; }

            if (extendedEntity.LogicalName != "gsc_cmn_extendedpricelistitem") { return; }

            if (context.Mode == 0) //Synchronous Plug-in
            {
                String message = context.MessageName;

                try
                {
                    var preImageUOM = preImageEntity.GetAttributeValue<EntityReference>("gsc_uomid") != null
                        ? preImageEntity.GetAttributeValue<EntityReference>("gsc_uomid").Id
                        : Guid.Empty;

                    var postImageUOM = postImageEntity.GetAttributeValue<EntityReference>("gsc_uomid") != null
                        ? postImageEntity.GetAttributeValue<EntityReference>("gsc_uomid").Id
                        : Guid.Empty;

                    var preImageAmount = preImageEntity.Contains("gsc_amount")
                        ? preImageEntity.GetAttributeValue<Money>("gsc_amount").Value
                        : 0;

                    var postImageAmount = postImageEntity.Contains("gsc_amount")
                        ? postImageEntity.GetAttributeValue<Money>("gsc_amount").Value
                        : 0;

                    if (preImageUOM != postImageUOM || preImageAmount != postImageAmount)
                    {
                        ExtendedPriceListItemHandler entityHandler = new ExtendedPriceListItemHandler(service, trace);
                        entityHandler.UpdatePriceListItem(extendedEntity);
                    }

                }

                catch (Exception ex)
                {
                    throw new InvalidPluginExecutionException(ex.Message);
                    // throw new InvalidPluginExecutionException(String.Concat("(Exception)\n", ex.Message, Environment.NewLine, ex.StackTrace));
                }
            }
        }
    }
}
