// <copyright file="PreVehicleInTransitTransferReceivingCreate.cs" company="">
// Copyright (c) 2017 All Rights Reserved
// </copyright>
// <author></author>
// <date>8/4/2017 2:57:19 PM</date>
// <summary>Implements the PreVehicleInTransitTransferReceivingCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.VehicleInTransitTransferReceiving;
    using GSC.Rover.DMS.BusinessLogic.Common;

    /// <summary>
    /// PreVehicleInTransitTransferReceivingCreate Plugin.
    /// </summary>    
    public class PreVehicleInTransitTransferReceivingCreate: Plugin
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreVehicleInTransitTransferReceivingCreate"/> class.
        /// </summary>
        public PreVehicleInTransitTransferReceivingCreate()
            : base(typeof(PreVehicleInTransitTransferReceivingCreate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(20, "Create", "gsc_iv_vehicleintransittransferreceiving", new Action<LocalPluginContext>(ExecutePreVehicleInTransitTransferReceivingCreate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePreVehicleInTransitTransferReceivingCreate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            // TODO: Implement your custom Plug-in business logic.

            IPluginExecutionContext context = localContext.PluginExecutionContext;
            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;
            Entity entity = (Entity)context.InputParameters["Target"];

            string message = context.MessageName;
            string error = "";

            try
            {
                VehicleInTransitTransferReceivingHandler receivingHandler = new VehicleInTransitTransferReceivingHandler(service, trace);

                Guid inTransitId = CommonHandler.GetEntityReferenceIdSafe(entity, "gsc_intransittransferid");
                EntityCollection inTransitCollection = CommonHandler.RetrieveRecordsByOneValue("gsc_iv_vehicleintransittransfer", "gsc_iv_vehicleintransittransferid", inTransitId, service,
                    null, Microsoft.Xrm.Sdk.Query.OrderType.Ascending, new[] { "gsc_sourcebranchid", "gsc_sourcesiteid", "gsc_viasiteid", "gsc_destinationbranchid" });

                entity = receivingHandler.PopulateSites(entity, inTransitCollection.Entities[0]);

                // check if in-transit transfer already exists.
                bool isDuplicate = receivingHandler.DetectDuplicate(entity);

                if (isDuplicate)
                {
                    throw new InvalidPluginExecutionException("Duplicate detected, In-Transit Transfer already exist.");
                }
            }
            catch (Exception ex)
            {
                throw new InvalidPluginExecutionException(ex.Message);
            }           
        }
    }
}
